### PR TITLE
Add support for new Messenger Platform social plugins

### PR DESCRIPTION
**Pull request by stevegeek**
Adds the new Facebook Messenger platform plugins to the plugin list, 'fb-send-to-messenger' and 'fb-messengermessageus'

See https://developers.facebook.com/docs/messenger-platform/plugin-reference

### CODE REVIEW

**Comment by pc035860** [comment]
@stevegeek The messenger platform plugins are only available in platform version `2.6`.
Can you upgrade the default SDK `version` parameter to `v2.6`?

https://github.com/pc035860/angular-easyfb/blob/master/src/angular-easyfb.js#L93

**Comment by stevegeek** [comment]
@pc035860 Ok thanks for the feedback. Done.

**Comment by pc035860** [comment]
Great! Thanks for the PR.

**Comment by stevegeek** [comment]
@pc035860 thanks, when do you think you might bump the version to add the support for this?

**Comment by pc035860** [comment]
@stevegeek Just published!

**Comment by stevegeek** [comment]
@pc035860 Thanks for the swift response! :)

**Pull request merged**
